### PR TITLE
Implement placeholder Navigation

### LINKED ISSUE #14: Implement placeholder Navigation
**Describe the ticket Here:**

In app/layout.tsx implement simple top navigation bar with placeholder links to: signin page, registration page, and profile page

These pages do not exist yet, you do not need to implement any more than just a dummy path (i.e. 'src/profile')

Feel free to use any template top-bar nav template you wish, this is merely a placeholder design

### PR DESCRIPTION
**Pull request by jclanting**
- Removed Next.js template
- Added components folder
- Added NavBar.tsx

Implemented navbar with placeholder links to signin, registration, and profile page

### CODE REVIEW

**Comment by SamShrubo** [comment]
Please change the merge destination from main to dev, and add cesar for the second required approver

**Review by SamShrubo — CHANGES_REQUESTED** [review]
Read other comment

**Comment by jclanting** [comment]
> Please change the merge destination from main to dev, and add cesar for the second required approver

**Comment by jclanting** [comment]
> Please change the merge destination from main to dev, and add cesar for the second required approver

Gotcha, all done

**Review by SamShrubo — DISMISSED** [review]

**Review by CesMag — DISMISSED** [review]

**Review by SamShrubo — APPROVED** [review]

**Pull request merged**
